### ISSUE TITLE
Project Structure inconsistency with Presenters 

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#109]
- move presenters to separate folder according to docs
- update unit tests threshold accordingly

**Comment by 0pdd** [comment]
@nesterone the puzzle [#111](https://github.com/zorko-io/zorko-designer/issues/111) is still not solved.

**Comment by 0pdd** [comment]
@nesterone the only puzzle [#111](https://github.com/zorko-io/zorko-designer/issues/111) is solved here.
