### ISSUE TITLE
Docs Inconsistency - rename features to slices

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#114]
- change exports to actins + reducer, so each slice would have their own 'Interface'

**Comment by 0pdd** [comment]
@nesterone 3 puzzles [#118](https://github.com/zorko-io/zorko-designer/issues/118), [#119](https://github.com/zorko-io/zorko-designer/issues/119), [#120](https://github.com/zorko-io/zorko-designer/issues/120) are still not solved.

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#118](https://github.com/zorko-io/zorko-designer/issues/118), [#119](https://github.com/zorko-io/zorko-designer/issues/119) are still not solved; solved: [#120](https://github.com/zorko-io/zorko-designer/issues/120).

**Comment by 0pdd** [comment]
@nesterone the puzzle [#118](https://github.com/zorko-io/zorko-designer/issues/118) is still not solved; solved: [#119](https://github.com/zorko-io/zorko-designer/issues/119), [#120](https://github.com/zorko-io/zorko-designer/issues/120).

**Comment by 0pdd** [comment]
@nesterone all 3 puzzles are solved here: [#118](https://github.com/zorko-io/zorko-designer/issues/118), [#119](https://github.com/zorko-io/zorko-designer/issues/119), [#120](https://github.com/zorko-io/zorko-designer/issues/120).
