### ISSUE TITLE
Audit application logger capabilities 

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#138]
- reducer, render etc

**Comment by 0pdd** [comment]
@nesterone 3 puzzles [#139](https://github.com/zorko-io/zorko-designer/issues/139), [#140](https://github.com/zorko-io/zorko-designer/issues/140), [#141](https://github.com/zorko-io/zorko-designer/issues/141) are still not solved.

**Comment by 0pdd** [comment]
@nesterone the puzzle [#141](https://github.com/zorko-io/zorko-designer/issues/141) is still not solved; solved: [#139](https://github.com/zorko-io/zorko-designer/issues/139), [#140](https://github.com/zorko-io/zorko-designer/issues/140).

**Comment by 0pdd** [comment]
@nesterone all 3 puzzles are solved here: [#139](https://github.com/zorko-io/zorko-designer/issues/139), [#140](https://github.com/zorko-io/zorko-designer/issues/140), [#141](https://github.com/zorko-io/zorko-designer/issues/141).
