### ISSUE TITLE
spec.md:37: Open Spec - list of screens in Zeplin

### ISSUE THREAD

**Issue by 0pdd** [zorko-io/zorko-designer#171]
The puzzle `136-1a494be8` from #136 has to be resolved: 

https://github.com/zorko-io/zorko-designer/blob/e4bef85080b84e1ebb33c5bacd3ea84bd91fe94f/docs/spec.md#L37-L37

The puzzle was created by nesterone on 09-Mar-20. 

Estimate: 2 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bazzika** [comment]
![Main_view](https://user-images.githubusercontent.com/12714598/76328441-f7ab6000-62f3-11ea-9097-7d80552934fb.png)
Main view

**Comment by bazzika** [comment]
![Tablet 2_examples](https://user-images.githubusercontent.com/12714598/76328479-03972200-62f4-11ea-9ddf-46be18367b21.png)
View with examples, not finished

**Comment by nesterone** [comment]
strange, but `png` files are corrupted, when I click to full view it shows me a lot of black regions

I think for that task three-screen would be enough 

`Main View without visualization` -> `Open Spec Dialog` -> `Main View with selected visualization`

**Comment by bazzika** [comment]
![list examples](https://user-images.githubusercontent.com/12714598/76421226-07867b00-63ac-11ea-8f3b-d2a818491bd8.png)
![Main view 2](https://user-images.githubusercontent.com/12714598/76421250-0f461f80-63ac-11ea-9d4f-8e9f88213d14.png)
Fixed background

**Comment by bazzika** [comment]
![Tablet example](https://user-images.githubusercontent.com/12714598/76537980-3e7d8f00-6487-11ea-907e-56c4ac61547c.png)

**Comment by 0pdd** [comment]
The puzzle `136-1a494be8` has disappeared from the source code, that's why I closed this issue.
