### ISSUE TITLE
Try PDD approach in the field

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#30]
- Integrate with 0ppd service
- Rewrite existing todos to 0pdd format
- Fix all initial todos

**Comment by 0pdd** [comment]
@nesterone 10 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40) are still not solved.

**Comment by 0pdd** [comment]
@nesterone 10 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41) are still not solved; solved: [#36](https://github.com/zorko-io/zorko-designer/issues/36).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41) are still not solved; solved: [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36).

**Comment by 0pdd** [comment]
@nesterone 8 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#53](https://github.com/zorko-io/zorko-designer/issues/53) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#41](https://github.com/zorko-io/zorko-designer/issues/41).

**Comment by 0pdd** [comment]
@nesterone 8 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#53](https://github.com/zorko-io/zorko-designer/issues/53) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52).

**Comment by 0pdd** [comment]
@nesterone 8 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#58](https://github.com/zorko-io/zorko-designer/issues/58) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52).

**Comment by 0pdd** [comment]
@nesterone 10 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#60](https://github.com/zorko-io/zorko-designer/issues/60) are still not solved; solved: [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58).

**Comment by 0pdd** [comment]
@nesterone 9 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#60](https://github.com/zorko-io/zorko-designer/issues/60) are still not solved; solved: [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58).

**Comment by 0pdd** [comment]
@nesterone 8 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59) are still not solved; solved: [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60).

**Comment by 0pdd** [comment]
@nesterone 7 puzzles [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59) are still not solved; solved: [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60).

**Comment by 0pdd** [comment]
@nesterone 7 puzzles [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#65](https://github.com/zorko-io/zorko-designer/issues/65) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60).

**Comment by 0pdd** [comment]
@nesterone 6 puzzles [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).

**Comment by 0pdd** [comment]
@nesterone 6 puzzles [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#70](https://github.com/zorko-io/zorko-designer/issues/70) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).

**Comment by 0pdd** [comment]
@nesterone 5 puzzles [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#70](https://github.com/zorko-io/zorko-designer/issues/70) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).

**Comment by nesterone** [comment]
closing this one as far as 'try' was done

**Comment by 0pdd** [comment]
@nesterone 4 puzzles [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#70](https://github.com/zorko-io/zorko-designer/issues/70) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).

**Comment by 0pdd** [comment]
@nesterone 3 puzzles [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#70](https://github.com/zorko-io/zorko-designer/issues/70) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).

**Comment by 0pdd** [comment]
@nesterone 3 puzzles [#133](https://github.com/zorko-io/zorko-designer/issues/133), [#59](https://github.com/zorko-io/zorko-designer/issues/59), [#70](https://github.com/zorko-io/zorko-designer/issues/70) are still not solved; solved: [#31](https://github.com/zorko-io/zorko-designer/issues/31), [#32](https://github.com/zorko-io/zorko-designer/issues/32), [#33](https://github.com/zorko-io/zorko-designer/issues/33), [#34](https://github.com/zorko-io/zorko-designer/issues/34), [#35](https://github.com/zorko-io/zorko-designer/issues/35), [#36](https://github.com/zorko-io/zorko-designer/issues/36), [#37](https://github.com/zorko-io/zorko-designer/issues/37), [#38](https://github.com/zorko-io/zorko-designer/issues/38), [#39](https://github.com/zorko-io/zorko-designer/issues/39), [#40](https://github.com/zorko-io/zorko-designer/issues/40), [#41](https://github.com/zorko-io/zorko-designer/issues/41), [#52](https://github.com/zorko-io/zorko-designer/issues/52), [#53](https://github.com/zorko-io/zorko-designer/issues/53), [#56](https://github.com/zorko-io/zorko-designer/issues/56), [#57](https://github.com/zorko-io/zorko-designer/issues/57), [#58](https://github.com/zorko-io/zorko-designer/issues/58), [#60](https://github.com/zorko-io/zorko-designer/issues/60), [#65](https://github.com/zorko-io/zorko-designer/issues/65).
