### ISSUE TITLE
selectAnalyticBoardTest.ts:15-16: Move to its own...

### ISSUE THREAD

**Issue by 0pdd** [zorko-io/zorko-designer#59]
The puzzle `32-2e7368a8` from #32 has to be resolved: 

https://github.com/zorko-io/zorko-designer/blob/9f27c0b81618320763b03e7086650aa43fcae9d5/src/features/analyticBoard/selectAnalyticBoardTest.ts#L15-L16

The puzzle was created by nesterone on 26-Dec-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nesterone** [comment]
looks like this one wasn`t caught by pdd bot, so closing it
