### ISSUE TITLE
Provide basic project documentation

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#72]
- provide project's README 
- define propose of the project, alternatives
- define how to contribute to the project
- define the architecture/structure of the project, how to write a test (unit tests/ integration tests)
- define license

**Comment by 0pdd** [comment]
@nesterone 7 puzzles [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90), [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95) are still not solved.

**Comment by 0pdd** [comment]
@nesterone 8 puzzles [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90), [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95), [#97](https://github.com/zorko-io/zorko-designer/issues/97) are still not solved.

**Comment by 0pdd** [comment]
@nesterone 7 puzzles [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95), [#97](https://github.com/zorko-io/zorko-designer/issues/97), [#99](https://github.com/zorko-io/zorko-designer/issues/99) are still not solved; solved: [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90).

**Comment by 0pdd** [comment]
@nesterone 6 puzzles [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95), [#97](https://github.com/zorko-io/zorko-designer/issues/97) are still not solved; solved: [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90), [#99](https://github.com/zorko-io/zorko-designer/issues/99).

**Comment by 0pdd** [comment]
@nesterone 5 puzzles [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95) are still not solved; solved: [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90), [#97](https://github.com/zorko-io/zorko-designer/issues/97), [#99](https://github.com/zorko-io/zorko-designer/issues/99).

**Comment by 0pdd** [comment]
@nesterone 4 puzzles [#92](https://github.com/zorko-io/zorko-designer/issues/92), [#93](https://github.com/zorko-io/zorko-designer/issues/93), [#94](https://github.com/zorko-io/zorko-designer/issues/94), [#95](https://github.com/zorko-io/zorko-designer/issues/95) are still not solved; solved: [#89](https://github.com/zorko-io/zorko-designer/issues/89), [#90](https://github.com/zorko-io/zorko-designer/issues/90), [#91](https://github.com/zorko-io/zorko-designer/issues/91), [#97](https://github.com/zorko-io/zorko-designer/issues/97), [#99](https://github.com/zorko-io/zorko-designer/issues/99).

**Comment by nesterone** [comment]
actually basic docs done, however contributing issues not documented yet

**Comment by 0pdd** [comment]
@nesterone 4 puzzles [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.
