### ISSUE TITLE
Low test coverage doesn't block the merge

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-designer#76]
- lowering of  code coverage doesn't broke the tests, especially for highly reusable modules  like 'common/util/createReducer.ts' or reducers, presenters and selectors

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#78](https://github.com/zorko-io/zorko-designer/issues/78), [#79](https://github.com/zorko-io/zorko-designer/issues/79) are still not solved.

**Comment by nesterone** [comment]
Configured build for pull request here #132, need to find a way for Github to block 'Merge Button'
if CI tests check were failed

**Comment by nesterone** [comment]
it's possible to restrict merge button for project collaborator, and even for administrator, however 
after that branch looked for pushes, so you stuck with fixes pushes, clicked all checkboxes,  it does't allow to push for protected branch with or without error state, just throws 'GH006'

However, as far as a collaborator is one person to allow merges, it doesn't an issue, because pushes from non-collaborators doesn't allow users to merge

**Comment by nesterone** [comment]
So, closing this one as far as build works and tests fail if low coverage reached

**Comment by 0pdd** [comment]
@nesterone the puzzle [#78](https://github.com/zorko-io/zorko-designer/issues/78) is still not solved; solved: [#79](https://github.com/zorko-io/zorko-designer/issues/79).

**Comment by 0pdd** [comment]
@nesterone the puzzle [#unknown]() is still not solved.
